#+TITLE: typewriter-mode: turn Emacs into a Text Adder
#+AUTHOR: Enrico Flor

[[https://elpa.gnu.org/packages/typewriter.html][https://elpa.gnu.org/packages/typewriter.svg]]

This package provides ~typewriter-mode~, a small minor mode that
deliberately handicaps Emacs to an extreme degree in order to provide
something as close as possible to the strict forward-only typewriter
experience.  Some find that the lack of editing facilities fosters a
state of concentration and focus that makes certain types of creative
writing more satisfying.

The package has several configuration options:

  - ~typewriter-preserve-undo-history~: If non-nil, you'll be able to
    undo edits if you turn ~typewriter-mode~.  Default is ~t~.

  - ~typewriter-recenter~: If non-nil, the line where cursor is at is
    recentered (the command ~recenter~ is called) after every licit
    keystroke.  Default is ~nil~.

  - ~typewriter-fill-column~: If ~nil~, your lines will be as long as
    you want.  Set to any integer =N=, emacs-turned-to-typewriter
    refuses to type anything once you reach column =N= until you
    press =RET= to open a new line.  Default is ~nil~.

  - ~typewriter-warning-bell-offset~: If your fill column is set, a
    physical /ding/ will sound this many characters before the margin to
    warn you that the carriage is about to jam.  Default is ~8~.

  - ~typewriter-show-chars-remaining~: If this and
    ~typewriter-fill-column~ are non-nil, the modeline will display how
    many characters are left in the current line until the fill column
    (the margin) is reached.  Default is ~t~.

  - ~typewriter-modeline-format~: Format string for the modeline
    indicator of remaining characters.  Default is =" [%d]"=.

  - ~typewriter-tab-width~: Self explanatory.  Default is ~8~.

There is also a *key jamming* mode that is controlled by a four
configuration options.  The only keystrokes that can ever jam are
those that correspond to a typewriter action: self-insert (inserting a
character), carriage return/newline, and moving the cursor back.  This
ensure that no matter the setup, things like ~M-x~ will never jam (at
least, not because of ~typewriter-mode~).  Whenever jamming occurs, a
message is displayed in the echo area and Emacs sleeps for a second,
so that you don't think something's wrong with your keyboard.  The
options are:

  - ~typewriter-jam-base-probability~: The minimal probability that any
    keystroke jams.  The default value of ~0.0~ ensures that no jamming
    ever occurs (regardless of how the other two variables are set).

  - ~typewriter-jam-repeat-boost~: A value that multiplies the base
    probability whenever the keystroke that is being attempted has
    jammed in the past (since the mode was turned on in the buffer).
    The default is ~1.0~ (no boost); any value less than ~1.0~ has the
    same effect as ~1.0~.

  - ~typewriter-jam-fast-sequence-boost~: A value that multiplies the
    base probability whenever the keystroke is occurring in a fast
    sequence.  The default is ~1.0~ (no boost); any value less than ~1.0~
    has the same effect as ~1.0~.

  - ~typewriter-fast-sequence-threshold~: Value, in seconds, that
    defines what keystroke sequences count as "fast" for the purposes
    of ~typewriter-jam-fast-sequence-boost~.  The default value is ~0.1~,
    which corresponds to 100 milliseconds.

There are four hooks available for the user to customize the typing
experience, no function is added to them by default.  The run *after*
successful completion of the corresponding action:

  - ~typewriter-insert-hook~

  - ~typewriter-carriage-return-hook~

  - ~typewriter-backward-char-hook~

  - ~typewriter-tab-hook~

Although no systematic test has been carried out, this package's
minimalism should ensure its compatibility with packages that change
the layout of text in the window, such as the fairly popular [[https://github.com/rnkn/olivetti][olivetti]],
or any configuration that (for instance) hides or alters element of
the emacs interface.

The package is on [[https://elpa.gnu.org/packages/typewriter.html][GNU Elpa]], and you can install it in the usual ways,
for instance:

#+begin_src emacs-lisp
(use-package typewriter)
#+end_src
